#pragma once

#define FSL_COMMA_SEPARATED_STRINGS_1(str) str
#define FSL_COMMA_SEPARATED_STRINGS_2(str) FSL_COMMA_SEPARATED_STRINGS_1(str), FSL_COMMA_SEPARATED_STRINGS_1(str)
#define FSL_COMMA_SEPARATED_STRINGS_4(str) FSL_COMMA_SEPARATED_STRINGS_2(str), FSL_COMMA_SEPARATED_STRINGS_2(str)
#define FSL_COMMA_SEPARATED_STRINGS_8(str) FSL_COMMA_SEPARATED_STRINGS_4(str), FSL_COMMA_SEPARATED_STRINGS_4(str)
#define FSL_COMMA_SEPARATED_STRINGS_16(str) FSL_COMMA_SEPARATED_STRINGS_8(str), FSL_COMMA_SEPARATED_STRINGS_8(str)
#define FSL_COMMA_SEPARATED_STRINGS_32(str) FSL_COMMA_SEPARATED_STRINGS_16(str), FSL_COMMA_SEPARATED_STRINGS_16(str)
#define FSL_COMMA_SEPARATED_STRINGS_64(str) FSL_COMMA_SEPARATED_STRINGS_32(str), FSL_COMMA_SEPARATED_STRINGS_32(str)
#define FSL_COMMA_SEPARATED_STRINGS_128(str) FSL_COMMA_SEPARATED_STRINGS_64(str), FSL_COMMA_SEPARATED_STRINGS_64(str)
#define FSL_COMMA_SEPARATED_STRINGS_256(str) FSL_COMMA_SEPARATED_STRINGS_128(str), FSL_COMMA_SEPARATED_STRINGS_128(str)
